### ISSUE TITLE
Why do we have c in some dispersion relations but not in the others?

### ISSUE THREAD

**Issue by razimantv** [arnaudon/netSALT#27]
`dispersion_relation_linear` divides by c

https://github.com/arnaudon/netSALT/blob/8d4eca604593155530495e7c50b8e391149e9380/netsalt/physics.py#L55

So does `dispersion_relation_resistance`

https://github.com/arnaudon/netSALT/blob/8d4eca604593155530495e7c50b8e391149e9380/netsalt/physics.py#L73-L75

But `dispersion_relation_dielectric` does not

https://github.com/arnaudon/netSALT/blob/8d4eca604593155530495e7c50b8e391149e9380/netsalt/physics.py#L87

And neither does `dispersion_relation_pump`

https://github.com/arnaudon/netSALT/blob/8d4eca604593155530495e7c50b8e391149e9380/netsalt/physics.py#L114-L119

**Comment by arnaudon** [comment]
Hello, 
because they are different parametrisations of the dispersion relation. 
The first 2 are generic ones, with wave speed c, whereas the last two are specific for dielectric medium, as we used in the paper. The second has some resistance, or damping term that depends on frequency, to model blood viscosity for example (capital C is called compliance). 
I hope this helps! (I should add more comments in the docstrings about that)

**Comment by razimantv** [comment]
They explicitly set c=1:
> We have taken the speed of light in a vacuum c to be unity; wave vector and frequency will be distinguished by the context.

I think it makes sense to do in theory but can be misleading comparing to experiment. But if you think it does not matter, feel free to close.

**Comment by arnaudon** [comment]
I guess depending on how one assigns units and interpret these, it may matter. I could add a params.get('c', 1) so users could use other conventions. Is this not 'standard' one?

**Comment by arnaudon** [comment]
I added c here: https://github.com/arnaudon/netSALT/pull/23/files
