### ISSUE TITLE
Internal workings of the function `_get_new_D0`

### ISSUE THREAD

**Issue by paul019** [arnaudon/netSALT#31]
I am currently working with netSALT on a machine learning project and trying to speed it up. For this purpose, I identified `find_threshold_lasing_modes` to be the most time consuming function in the whole process, so I try to understand it better. This function goes back and forth between approximating the modes for higher pump values and then using Brownian Ratchet.

For the first step (mode approximation), the function `_get_new_D0 ` is called repetitively:

https://github.com/arnaudon/netSALT/blob/fa0a2aed237f134f80aa88dd6a8afb5f7d0707ca/netsalt/modes.py#L788-L802

I tried to understand what is going on here, but I have a hard time in doing so. **Could someone explain to me how this function works?** I would really appreciate it.

# Some investigations

I did some investigation of this function with a partial illumination of a Voronoi network. I looked at the mode trajectories (see figure 1). I discovered that some mode trajectories are unusually long (I marked them in black).

I went on to plot the value of D0 against the iteration number for such a "bad mode" (see figure 2) and for a "good mode" (see figure 3).

# Attached figures

<details>
  <summary><b>Figure 1 (Mode trajectories)</b></summary>
<IMG src=https://github.com/user-attachments/assets/af9806d4-180e-4785-b97f-e547d1835bde>
</details>

<details>
  <summary><b>Figure 2 (Progression of D0 for a "bad mode")</b></summary>
<IMG src=https://github.com/user-attachments/assets/96af38cc-c47e-40c3-a091-0bd43b65452c>
</details>

<details>
  <summary><b>Figure 3 (Progression of D0 for a "good mode")</b></summary>
<IMG src=https://github.com/user-attachments/assets/c2319d00-7872-423a-823d-377d41e5e53b>
</details>

**Comment by arnaudon** [comment]
Hello! 

I'm trying to recall what I did here, its not easy indeed ;) So it is supposed to find  the D0 to get to lasing (Imk=0), and because the mode location in the complex plane is nonlinear wrt D0, we do it incrementally. We have a linear approximation for the wavenumber and lasing D0, but as it is linear, it only works for small D0 increments. So what we do is to take steps in D0 that are not larger than some `D0_steps`, but can be smaller if we get near the threshold. The abs and the if are not really necessary, probably i added this for some weird edge cases I encountered, but I don't remember.

For the fact that sometimes it is slow, I remembered seeing these sometimes, but I never fully investigated it. It seems to be oscillating, but I don't know why... probably something quite unlikely from the linear approximation of this specific mode. You can try to play with this function, maybe reducing the `increment` by like 0.8, to see if this kills the oscillations or not.

I hope this helps! If this is really a blocker, I can try to take a look if you have some easy repro, it would be nice to improve this if it happens often!

Have a nice evening,
Alexis

**Comment by paul019** [comment]
Thank you! I was mainly confused by the `if` and the `abs`.

I might try to re-implement the function `_get_new_D0` using a binary search once the real axis is crossed (I have a point below the real axis and one above the real axis and can do binary search in between then). For my purpose, it might even be enough to do a linear approximation between the point directly above and below the real axis.
